inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'example/db/schema.rb'
    - 'example/bin/*'

Style/StringLiterals:
  Enabled: false


Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: false
