inherit_from: .rubocop_todo.yml

Style/StringLiterals:
  Enabled: false

AllCops:                                                     
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: false
